# Generated by Django 4.2.2 on 2023-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creted',
            new_name='created',
        ),
    ]
